pipeline {
    agent any

    options {
        //Indica las marcas de tiempo en los logs de jenkins
        timestamps()
    }

    environment {
        RELEASE = '0.0.1'
    }

    stages {
        stage('Build') {
            environment {
                LOG_LEVEL = 'INFO'
            }
            parallel {
                stage('linux-arm64') {
                    steps { 
                        echo "Building release ${Release} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                        sh 'sleep 1'
                        echo "build done"
                    }
                }

                stage('linux-amd64') {
                    steps { 
                        echo "Building release ${Release} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                        sh 'sleep 3'
                        echo "build done"
                    }
                }

                stage('windows-arm64') {
                    steps { 
                        echo "Building release ${Release} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                        sh 'sleep 10'
                        echo "build done"
                    }
                }
           }
        }

        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}"
            }
        }

        stage('Deploy') {
            input {
                message "Deploy?"
                ok "Do It!"
                parameters {
                    string(
                        name: 'TARGET_ENVIRONMENT',
                        defaultValue: 'PROD',
                        description: 'Target deployment environment' 
                    )
                }
            }
            steps {               
                echo "Deploying release ${RELEASE} ${TARGET_ENVIRONMENT}"
            }
        }
    }

    post {
        always {
            echo 'Print wether deploy happened or not, success or failure'
        }
    }
}