pipeline {
    agent any

    environment{
        DEMO = '1.3'
    }

    stages {
        stage('stage-1') {            
            steps {
                //Se situa sobre el directorio
                dir('01-intro') {
                    echo "This is the build number $BUILD_NUMBER of demo $DEMO"
                    sh '''
                      ls
                      echo "Using a multi-line shell step"
                      chmod +x ./test.sh
                      ./test.sh
                    '''
                }
            }
        }
    }
}
