pipeline{
    agent {
       dockerfile {
           dir '06-docker/solution'
       }
    }
    stages {
        stage('Verify') {
            steps {
                sh'''
                    node --version
                    npm --version
                '''
            }

        }
        stage('Build') {
            steps {
                dir('./06-docker/solution') {
                    sh 'docker build -t franjfgcarmo/jenkins-pipeline-demos:0.0.1 .'
                }
            }
        }
        stage('Smoke Test') {
            steps {
                dir('./06-docker/solution') {
                    sh 'docker run franjfgcarmo/jenkins-pipeline-demos:0.0.1'
                }                
            }
        }
    }   
}