pipeline{
    agent {
       dockerfile {
           filename '06-docker/solution/Dockerfile'
    }
    stages {
        stage('Verify') {
            steps {
                sh'''
                    node --version
                    npm --version
                '''
            }

        }
        stage('Build') {
            steps {
                dir('./06-docker/solution') {
                sh '''
                    npm install
                    npm run build
                '''
                }
            }
        }
        stage('Unit test') {
            steps {
                dir('./06-docker/solution') {
                    sh 'npm test'
                }
            }
        }
    }   
}