pipeline{
    agent {
       dockerfile {
           filename '06-docker/solution/Dockerfile'
    }
    stages {
        stage('Verify') {
            steps {
                sh'''
                    node --version
                    npm --version
                '''
            }

        }
        stage('Build') {
            steps {
                sh 'docker build -t franjfgcarmo/jenkins-pipeline-demos:0.0.1 .'
            }
        }
        stage('Smoke Test') {
            steps {
                sh 'docker run franjfgcarmo/jenkins-pipeline-demos:0.0.1'
            }
        }
    }   
}