pipeline {
    agent any
    environment {
        //Directiva de script
        VERSION = sh(
            script: 'cd ./05-pipelines/solution && npx -c \'echo $npm_package_version\'',
            returnStdout: true
        ).trim()
        VERSION_RC = 'rc.2'
    }

    stages {
        stage('Audit tools') {
            steps {
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
            }
        }

        stage('Build') {
            steps {
                dir('./05-pipelines/solution') {
                    echo "Build version ${VERSION} with suffix: ${VERSION_RC}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }

        stage('Unit test') {
            steps {
                dir('./05-pipelines/solution') {
                    sh 'npm test'
                }  
            }             
        }
    }
}