pipeline {
    agent any

    stages {
        stage('Compile') {
              dir('./calculator') {
                  steps {
                      sh './calculator/gradlew compileJava'
                  }
              }
        }
        stage('Test') {
                steps {
                    sh './calculator/gradlew test'
                }
        }
    }
}