pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                dir('./calculator/src/main/java') {
                    sh 'ls'
                    sh './gradlew compileJava'
                }
            }
        }
        stage('Test') {
            steps {
                dir('./calculator/src/test/java') {
                    sh './gradlew test'
                }                    
            }
        }        
    }
}