pipeline {
    agent any

    stages {
        stage('Compile') {
                  steps {
                    dir('./calculator') {
                        sh './calculator/gradlew compileJava'
                    }
                  }
              }
        }
        stage('Test') {
                steps {
                    dir('./calculator') {
                        sh './gradlew test'
                    }                    
                }
        }
    }
}