pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                dir('./calculator') {
                    sh 'chmod +x gradlew'
                    sh './gradlew compileJava'
                }
            }
        }
        stage('Test') {
            steps {
                dir('./calculator') {
                    sh 'chmod +x gradlew'
                    sh './gradlew test'
                }                    
            }
        }        
    }
}